minor tweaks in husky

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,1 +1,5 @@
-npm run build
+echo "Current directory: $(pwd)"
+npm run build && echo "🚀 Build successful!" || (
+  echo "🔥 Build failed!"
+  false
+)
